table Dim_Aliado
	lineageTag: 5b34de0e-28ad-4ec0-96a9-70e861522753

	column AliadoKey
		dataType: string
		lineageTag: 6986647c-9540-4e03-929f-f12c1bbd8ce5
		summarizeBy: none
		sourceColumn: AliadoKey

	column Descripcion
		dataType: string
		lineageTag: ce0d408f-707e-4746-b460-e54ddac2f915
		summarizeBy: none
		sourceColumn: Descripcion

	column Pusher
		dataType: string
		lineageTag: 67713287-b930-45f7-b747-7687f0471a3e
		summarizeBy: none
		sourceColumn: Pusher

	column Estado_Clasificacion
		dataType: string
		lineageTag: 211f4532-83b8-40fb-8f26-1bc6d6979a58
		summarizeBy: none
		sourceColumn: Estado_Clasificacion

	partition Dim_Aliado = m
		mode: import
		source =
				let
					FilasValidas = Table.SelectRows(AltasTeResuelve_Limpio, each [EstadoFila] = "Valida" and [Descripcion] <> null and [Descripcion] <> ""),
					Descripciones = Table.Distinct(Table.SelectColumns(FilasValidas, {"AliadoKey", "Descripcion"})),
					ConMapa = Table.NestedJoin(Descripciones, {"Descripcion"}, Map_PusherAliado, {"Descripcion"}, "Mapeo", JoinKind.LeftOuter),
					ConPusher = Table.ExpandTableColumn(ConMapa, "Mapeo", {"Pusher"}, {"PusherMapeado"}),
					PusherAsignado = Table.AddColumn(ConPusher, "Pusher", each if [PusherMapeado] = null then "Sin asignar" else [PusherMapeado], type text),
					ConEstadoClasificacion = Table.AddColumn(PusherAsignado, "Estado_Clasificacion", each if [Pusher] = "Sin asignar" then "Pendiente" else "Clasificado", type text),
					ColumnasFinales = Table.SelectColumns(ConEstadoClasificacion, {"AliadoKey", "Descripcion", "Pusher", "Estado_Clasificacion"}),
					TiposAplicados = Table.TransformColumnTypes(ColumnasFinales, {{"AliadoKey", type text}, {"Descripcion", type text}, {"Pusher", type text}, {"Estado_Clasificacion", type text}}),
					Ordenado = Table.Sort(TiposAplicados, {{"Descripcion", Order.Ascending}})
				in
					Ordenado

	annotation PBI_ResultType = Table
