table Dim_Calendario
	lineageTag: 6805cc1c-501e-4506-822c-e334d09dc801

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7d428763-ccc6-4c64-a25b-922783bf3584
		summarizeBy: none
		sourceColumn: Fecha

	column Anio
		dataType: int64
		lineageTag: 4871c017-0e7a-40e2-8ccb-41553c8287a4
		summarizeBy: sum
		sourceColumn: Anio

		annotation SummarizationSetBy = Automatic

	column MesNumero
		dataType: int64
		lineageTag: e594b797-a994-4d9a-ab2e-3b6529c78474
		summarizeBy: sum
		sourceColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column MesNombre
		dataType: string
		lineageTag: 9bb63839-8f98-4d03-85b3-7f969853f9b8
		summarizeBy: none
		sourceColumn: MesNombre

	column AnioMes
		dataType: string
		lineageTag: 3ef94408-567a-4c98-b37a-8eeaed16c550
		summarizeBy: none
		sourceColumn: AnioMes

	column Trimestre
		dataType: int64
		lineageTag: f9559881-1a0b-40a9-b42e-f5cdab93815d
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column SemanaAnio
		dataType: int64
		lineageTag: a081a804-2e68-44a3-a058-714646f5a705
		summarizeBy: sum
		sourceColumn: SemanaAnio

		annotation SummarizationSetBy = Automatic

	column DiaMes
		dataType: int64
		lineageTag: 02879ade-58c3-484b-8673-e6e0dcd39b1e
		summarizeBy: sum
		sourceColumn: DiaMes

		annotation SummarizationSetBy = Automatic

	column DiaSemanaNumero
		dataType: int64
		lineageTag: 22c95e9d-ce0a-4aaa-afa0-7d26c408869c
		summarizeBy: sum
		sourceColumn: DiaSemanaNumero

		annotation SummarizationSetBy = Automatic

	column DiaSemanaNombre
		dataType: string
		lineageTag: 1741c797-f313-4cc6-a815-e57de2c7ba56
		summarizeBy: none
		sourceColumn: DiaSemanaNombre

	column EsFinDeSemana
		dataType: boolean
		lineageTag: 8448f5aa-eb8e-4852-9d25-4e2782da0125
		summarizeBy: none
		sourceColumn: EsFinDeSemana

	column Periodo_Gestion
		dataType: string
		summarizeBy: none
		sourceColumn: Periodo_Gestion

	column Estado_Periodo
		dataType: string
		summarizeBy: none
		sourceColumn: Estado_Periodo

	column Es_Periodo_Comparable
		dataType: boolean
		summarizeBy: none
		sourceColumn: Es_Periodo_Comparable

	column 'Fecha Eje' = FORMAT(DAY(Dim_Calendario[Fecha]), "00") & "/" & FORMAT(MONTH(Dim_Calendario[Fecha]), "00")
		dataType: string
		lineageTag: 617bae76-9ae8-4b37-9af8-f1782759e834
		summarizeBy: none
		sortByColumn: Fecha

	partition Dim_Calendario = m
		mode: import
		source =
				let
					FechasCalidadValidas = List.RemoveNulls(Fact_CalidadLlamadas[Fecha]),
					FechasCapacitacionValidas = List.RemoveNulls(Fact_SatisfaccionCapacitacion[Fecha]),
					FechasMotivacionValidas = List.RemoveNulls(Fact_MotivacionActividad[Fecha]),
					FechasAltasValidas = List.RemoveNulls(Fact_AltasTeResuelve[FechaAlta]),
					FechaMinCalidad = if List.IsEmpty(FechasCalidadValidas) then null else List.Min(FechasCalidadValidas),
					FechaMinCapacitacion = if List.IsEmpty(FechasCapacitacionValidas) then null else List.Min(FechasCapacitacionValidas),
					FechaMinMotivacion = if List.IsEmpty(FechasMotivacionValidas) then null else List.Min(FechasMotivacionValidas),
					FechaMinAltas = if List.IsEmpty(FechasAltasValidas) then null else List.Min(FechasAltasValidas),
					FechaMaxCalidad = if List.IsEmpty(FechasCalidadValidas) then null else List.Max(FechasCalidadValidas),
					FechaMaxCapacitacion = if List.IsEmpty(FechasCapacitacionValidas) then null else List.Max(FechasCapacitacionValidas),
					FechaMaxMotivacion = if List.IsEmpty(FechasMotivacionValidas) then null else List.Max(FechasMotivacionValidas),
					FechaMaxAltas = if List.IsEmpty(FechasAltasValidas) then null else List.Max(FechasAltasValidas),
					FechasMinimasValidas = List.RemoveNulls({FechaMinCalidad, FechaMinCapacitacion, FechaMinMotivacion, FechaMinAltas}),
					FechasMaximasValidas = List.RemoveNulls({FechaMaxCalidad, FechaMaxCapacitacion, FechaMaxMotivacion, FechaMaxAltas}),
					FechaMinima = if List.IsEmpty(FechasMinimasValidas) then Date.From(DateTime.LocalNow()) else List.Min(FechasMinimasValidas),
					FechaActual = Date.From(DateTime.LocalNow()),
					FechaMaximaFuentes = if List.IsEmpty(FechasMaximasValidas) then FechaActual else List.Max(FechasMaximasValidas),
					FechaMaxima = List.Max({FechaActual, FechaMaximaFuentes}),
					PeriodosComerciales = List.Transform(FechasAltasValidas, each Date.Year(Date.From(_)) * 100 + Date.Month(Date.From(_))),
					MaximoPeriodoComercial = if List.IsEmpty(PeriodosComerciales) then null else List.Max(PeriodosComerciales),
					CantidadDias = Duration.Days(FechaMaxima - FechaMinima) + 1,
					ListaFechas = List.Dates(FechaMinima, CantidadDias, #duration(1, 0, 0, 0)),
					TablaFechas = Table.FromList(ListaFechas, Splitter.SplitByNothing(), {"Fecha"}, null, ExtraValues.Error),
					TipoFechaAplicado = Table.TransformColumnTypes(TablaFechas, {{"Fecha", type date}}),
					ColumnaAnio = Table.AddColumn(TipoFechaAplicado, "Anio", each Date.Year([Fecha]), Int64.Type),
					ColumnaMesNumero = Table.AddColumn(ColumnaAnio, "MesNumero", each Date.Month([Fecha]), Int64.Type),
					ColumnaMesNombre = Table.AddColumn(ColumnaMesNumero, "MesNombre", each Date.MonthName([Fecha], "es-CO"), type text),
					ColumnaAnioMes = Table.AddColumn(ColumnaMesNombre, "AnioMes", each Date.ToText([Fecha], "yyyy-MM"), type text),
					ColumnaTrimestre = Table.AddColumn(ColumnaAnioMes, "Trimestre", each Date.QuarterOfYear([Fecha]), Int64.Type),
					ColumnaSemanaAnio = Table.AddColumn(ColumnaTrimestre, "SemanaAnio", each Date.WeekOfYear([Fecha]), Int64.Type),
					ColumnaDiaMes = Table.AddColumn(ColumnaSemanaAnio, "DiaMes", each Date.Day([Fecha]), Int64.Type),
					ColumnaDiaSemanaNumero = Table.AddColumn(ColumnaDiaMes, "DiaSemanaNumero", each Date.DayOfWeek([Fecha], Day.Monday) + 1, Int64.Type),
					ColumnaDiaSemanaNombre = Table.AddColumn(ColumnaDiaSemanaNumero, "DiaSemanaNombre", each Date.DayOfWeekName([Fecha], "es-CO"), type text),
					ColumnaEsFinDeSemana = Table.AddColumn(ColumnaDiaSemanaNombre, "EsFinDeSemana", each Date.DayOfWeek([Fecha], Day.Monday) >= 5, type logical),
					ColumnaPeriodoGestion = Table.AddColumn(ColumnaEsFinDeSemana, "Periodo_Gestion", each if [Fecha] < Fecha_Inicio_Gestion_Pusher_2 then "Antes de gestion" else "Desde inicio gestion", type text),
					ColumnaEstadoPeriodo = Table.AddColumn(ColumnaPeriodoGestion, "Estado_Periodo", each
						let PeriodoFila = Date.Year([Fecha]) * 100 + Date.Month([Fecha])
						in
							if PeriodoFila <= Int64.From(Periodo_Corte_Comercial) then "Cerrado"
							else if MaximoPeriodoComercial <> null and PeriodoFila = MaximoPeriodoComercial then "En curso"
							else if MaximoPeriodoComercial <> null and PeriodoFila < MaximoPeriodoComercial then "Posterior al corte sin validar"
							else "Posterior a fuente", type text),
					ColumnaEsPeriodoComparable = Table.AddColumn(ColumnaEstadoPeriodo, "Es_Periodo_Comparable", each Date.Year([Fecha]) * 100 + Date.Month([Fecha]) <= Int64.From(Periodo_Corte_Comercial), type logical),
					TipoFechaFinal = Table.TransformColumnTypes(ColumnaEsPeriodoComparable, {{"Fecha", type datetime}})
				in
					TipoFechaFinal

