table Dim_AsignacionPusherPeriodo
	lineageTag: cab4baa2-8874-44c6-89c0-00d14c63d619

	column PeriodoAliadoKey
		dataType: string
		isHidden
		isUnique
		isKey
		isNullable: false
		lineageTag: ed643d70-9de3-488f-93e1-e3c93c600720
		summarizeBy: none
		sourceColumn: PeriodoAliadoKey

	column AnioMes
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 242917ed-4be9-4241-9701-a968b49039c2
		summarizeBy: none
		sourceColumn: AnioMes

	column AliadoKey
		dataType: string
		isHidden
		isNullable: false
		lineageTag: 64767fef-329d-45f8-a85b-59cedc53f1de
		summarizeBy: none
		sourceColumn: AliadoKey

	column PusherPeriodo
		dataType: string
		isNullable: false
		lineageTag: ae981731-1dda-4877-8df9-484c985dfa9e
		summarizeBy: none
		sourceColumn: PusherPeriodo

	column TipoAsignacion
		dataType: string
		isNullable: false
		lineageTag: 11b7e061-04c7-4aaa-8a17-cc8561cd290a
		summarizeBy: none
		sourceColumn: TipoAsignacion

	column PusherAsignacion
		dataType: string
		isNullable: false
		lineageTag: 91eea1f8-84d5-4462-a5be-b99a2947273e
		summarizeBy: none
		sourceColumn: PusherAsignacion

	column TipoReglaAsignacion
		dataType: string
		isNullable: false
		lineageTag: a721684f-81aa-4767-a1c0-eda883e35724
		summarizeBy: none
		sourceColumn: TipoReglaAsignacion

	partition Dim_AsignacionPusherPeriodo = m
		mode: import
		source =
				let
				    AltasConAnioMes = Table.AddColumn(
				        Fact_AltasTeResuelve,
				        "AnioMes",
				        each Date.Year(Date.From([FechaAlta])) * 100 + Date.Month(Date.From([FechaAlta])),
				        Int64.Type
				    ),
				    CombinacionesAltas = Table.Distinct(
				        Table.SelectColumns(AltasConAnioMes, {"PeriodoAliadoKey", "AnioMes", "AliadoKey"})
				    ),
				    CombinacionesMetas = Table.Distinct(
				        Table.SelectColumns(Fact_MetasComerciales, {"PeriodoAliadoKey", "AnioMes", "AliadoKey"})
				    ),
				    Combinaciones = Table.Distinct(Table.Combine({CombinacionesAltas, CombinacionesMetas})),
				    ConClasificacionBase = Table.NestedJoin(
				        Combinaciones,
				        {"AliadoKey"},
				        Dim_Aliado,
				        {"AliadoKey"},
				        "ClasificacionBase",
				        JoinKind.LeftOuter
				    ),
				    PusherBaseExpandido = Table.ExpandTableColumn(
				        ConClasificacionBase,
				        "ClasificacionBase",
				        {"Pusher"},
				        {"PusherBase"}
				    ),
				    PusherBaseNormalizado = Table.TransformColumns(
				        PusherBaseExpandido,
				        {{"PusherBase", each if _ = null then "Sin asignar" else _, type text}}
				    ),
				    ConOverride = Table.NestedJoin(
				        PusherBaseNormalizado,
				        {"AnioMes", "AliadoKey"},
				        Map_AsignacionPusherPeriodo,
				        {"AnioMes", "AliadoKey"},
				        "Override",
				        JoinKind.LeftOuter
				    ),
				    OverrideExpandido = Table.ExpandTableColumn(
				        ConOverride,
				        "Override",
				        {"PusherPeriodo"},
				        {"PusherOverride"}
				    ),
				    ConPusherPeriodo = Table.AddColumn(
				        OverrideExpandido,
				        "PusherPeriodo",
				        each if [PusherOverride] <> null then [PusherOverride] else [PusherBase],
				        type text
				    ),
				    ConTipoAsignacion = Table.AddColumn(
				        ConPusherPeriodo,
				        "TipoAsignacion",
				        each if [PusherOverride] <> null then "Override temporal" else "Clasificacion base",
				        type text
				    ),
				    ConAsignacionFuente = Table.NestedJoin(
				        ConTipoAsignacion,
				        {"AliadoKey"},
				        Map_AsignacionPusherFuente,
				        {"AliadoKey"},
				        "AsignacionFuente",
				        JoinKind.LeftOuter
				    ),
				    AsignacionFuenteExpandida = Table.ExpandTableColumn(
				        ConAsignacionFuente,
				        "AsignacionFuente",
				        {"Pusher", "TipoRegla"},
				        {"PusherAsignacionFuente", "TipoReglaAsignacionFuente"}
				    ),
				    ConPusherAsignacion = Table.AddColumn(
				        AsignacionFuenteExpandida,
				        "PusherAsignacion",
				        each if [PusherOverride] <> null then [PusherOverride] else if [PusherAsignacionFuente] = null then "Sin asignar" else [PusherAsignacionFuente],
				        type text
				    ),
				    ConTipoReglaAsignacion = Table.AddColumn(
				        ConPusherAsignacion,
				        "TipoReglaAsignacion",
				        each if [PusherOverride] <> null then "Override temporal" else if [TipoReglaAsignacionFuente] = null then "Sin coincidencia" else [TipoReglaAsignacionFuente],
				        type text
				    ),
				    ColumnasFinales = Table.SelectColumns(
				        ConTipoReglaAsignacion,
				        {"PeriodoAliadoKey", "AnioMes", "AliadoKey", "PusherPeriodo", "TipoAsignacion", "PusherAsignacion", "TipoReglaAsignacion"}
				    ),
				    TiposAplicados = Table.TransformColumnTypes(
				        ColumnasFinales,
				        {
				            {"PeriodoAliadoKey", type text},
				            {"AnioMes", Int64.Type},
				            {"AliadoKey", type text},
				            {"PusherPeriodo", type text},
				            {"TipoAsignacion", type text},
				            {"PusherAsignacion", type text},
				            {"TipoReglaAsignacion", type text}
				        }
				    ),
				    Ordenado = Table.Sort(TiposAplicados, {{"AnioMes", Order.Ascending}, {"AliadoKey", Order.Ascending}})
				in
				    Ordenado
