table Dim_Calendario
	lineageTag: 6805cc1c-501e-4506-822c-e334d09dc801

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7d428763-ccc6-4c64-a25b-922783bf3584
		summarizeBy: none
		sourceColumn: Fecha

	column Anio
		dataType: int64
		lineageTag: 4871c017-0e7a-40e2-8ccb-41553c8287a4
		summarizeBy: none
		sourceColumn: Anio

	column MesNumero
		dataType: int64
		lineageTag: e594b797-a994-4d9a-ab2e-3b6529c78474
		summarizeBy: none
		sourceColumn: MesNumero

	column MesNombre
		dataType: string
		lineageTag: 9bb63839-8f98-4d03-85b3-7f969853f9b8
		summarizeBy: none
		sourceColumn: MesNombre

	column AnioMes
		dataType: string
		lineageTag: 3ef94408-567a-4c98-b37a-8eeaed16c550
		summarizeBy: none
		sourceColumn: AnioMes

	column Trimestre
		dataType: int64
		lineageTag: f9559881-1a0b-40a9-b42e-f5cdab93815d
		summarizeBy: none
		sourceColumn: Trimestre

	column SemanaAnio
		dataType: int64
		lineageTag: a081a804-2e68-44a3-a058-714646f5a705
		summarizeBy: none
		sourceColumn: SemanaAnio

	column DiaMes
		dataType: int64
		lineageTag: 02879ade-58c3-484b-8673-e6e0dcd39b1e
		summarizeBy: none
		sourceColumn: DiaMes

	column DiaSemanaNumero
		dataType: int64
		lineageTag: 22c95e9d-ce0a-4aaa-afa0-7d26c408869c
		summarizeBy: none
		sourceColumn: DiaSemanaNumero

	column DiaSemanaNombre
		dataType: string
		lineageTag: 1741c797-f313-4cc6-a815-e57de2c7ba56
		summarizeBy: none
		sourceColumn: DiaSemanaNombre

	column EsFinDeSemana
		dataType: boolean
		lineageTag: 8448f5aa-eb8e-4852-9d25-4e2782da0125
		summarizeBy: none
		sourceColumn: EsFinDeSemana

	partition Dim_Calendario = m
		mode: import
		source =
				let
					FechaMinCalidad = List.Min(Fact_CalidadLlamadas[Fecha]),
					FechaMinCapacitacion = List.Min(Fact_SatisfaccionCapacitacion[Fecha]),
					FechaMinMotivacion = List.Min(Fact_MotivacionActividad[Fecha]),
					FechaMinima = List.Min({FechaMinCalidad, FechaMinCapacitacion, FechaMinMotivacion}),
					FechaMaxima = Date.From(DateTime.LocalNow()),
					CantidadDias = Duration.Days(FechaMaxima - FechaMinima) + 1,
					ListaFechas = List.Dates(FechaMinima, CantidadDias, #duration(1, 0, 0, 0)),
					TablaFechas = Table.FromList(ListaFechas, Splitter.SplitByNothing(), {"Fecha"}, null, ExtraValues.Error),
					TipoFechaAplicado = Table.TransformColumnTypes(TablaFechas, {{"Fecha", type date}}),
					ColumnaAnio = Table.AddColumn(TipoFechaAplicado, "Anio", each Date.Year([Fecha]), Int64.Type),
					ColumnaMesNumero = Table.AddColumn(ColumnaAnio, "MesNumero", each Date.Month([Fecha]), Int64.Type),
					ColumnaMesNombre = Table.AddColumn(ColumnaMesNumero, "MesNombre", each Date.MonthName([Fecha], "es-CO"), type text),
					ColumnaAnioMes = Table.AddColumn(ColumnaMesNombre, "AnioMes", each Date.ToText([Fecha], "yyyy-MM"), type text),
					ColumnaTrimestre = Table.AddColumn(ColumnaAnioMes, "Trimestre", each Date.QuarterOfYear([Fecha]), Int64.Type),
					ColumnaSemanaAnio = Table.AddColumn(ColumnaTrimestre, "SemanaAnio", each Date.WeekOfYear([Fecha]), Int64.Type),
					ColumnaDiaMes = Table.AddColumn(ColumnaSemanaAnio, "DiaMes", each Date.Day([Fecha]), Int64.Type),
					ColumnaDiaSemanaNumero = Table.AddColumn(ColumnaDiaMes, "DiaSemanaNumero", each Date.DayOfWeek([Fecha], Day.Monday) + 1, Int64.Type),
					ColumnaDiaSemanaNombre = Table.AddColumn(ColumnaDiaSemanaNumero, "DiaSemanaNombre", each Date.DayOfWeekName([Fecha], "es-CO"), type text),
					ColumnaEsFinDeSemana = Table.AddColumn(ColumnaDiaSemanaNombre, "EsFinDeSemana", each Date.DayOfWeek([Fecha], Day.Monday) >= 5, type logical),
					TipoFechaFinal = Table.TransformColumnTypes(ColumnaEsFinDeSemana, {{"Fecha", type datetime}})
				in
					TipoFechaFinal

