table Fact_SatisfaccionCapacitacion

	column FechaHora
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: FechaHora

	column CallCenter
		dataType: string
		summarizeBy: none
		sourceColumn: CallCenter

	column Jornada
		dataType: string
		summarizeBy: none
		sourceColumn: Jornada

	column NombreAsesor
		dataType: string
		summarizeBy: none
		sourceColumn: NombreAsesor

	column NombreLider
		dataType: string
		summarizeBy: none
		sourceColumn: NombreLider

	column NombreFormador
		dataType: string
		summarizeBy: none
		sourceColumn: NombreFormador

	column SatisfaccionGeneral
		dataType: double
		summarizeBy: none
		sourceColumn: SatisfaccionGeneral

	column Claridad
		dataType: double
		summarizeBy: none
		sourceColumn: Claridad

	column Utilidad
		dataType: double
		summarizeBy: none
		sourceColumn: Utilidad

	column Dinamismo
		dataType: double
		summarizeBy: none
		sourceColumn: Dinamismo

	column Duracion
		dataType: string
		summarizeBy: none
		sourceColumn: Duracion

	column Comentario
		dataType: string
		summarizeBy: none
		sourceColumn: Comentario

	column Fecha
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Fecha

	partition Fact_SatisfaccionCapacitacion = m
		mode: import
		source =
				let
					Origen = SatisfaccionCapacitacion_Limpio,
					ColumnasRenombradas = Table.RenameColumns(Origen, {
						{"Timestamp", "FechaHora"},
						{"¿En qué call center trabajas?", "CallCenter"},
						{"¿En qué jornada participaste?", "Jornada"},
						{"Nombre completo (mayúscula)", "NombreAsesor"},
						{"Nombre del líder (Mayúscula)", "NombreLider"},
						{"Nombre formador", "NombreFormador"},
						{"¿Qué tan satisfecho/a quedaste con la capacitación?", "SatisfaccionGeneral"},
						{"La capacitación fue clara y fácil de entender.", "Claridad"},
						{"El contenido fue útil para mi gestión comercial.", "Utilidad"},
						{"La capacitación fue dinámica y mantuvo mi atención.", "Dinamismo"},
						{"Duración", "Duracion"},
						{"¿Qué mejorarías o qué información te gustaría para una próxima visita?", "Comentario"}
					}),
					NombresPersonaNormalizados = Table.TransformColumns(ColumnasRenombradas, {
						{"NombreAsesor", each if _ = null then _ else Text.Proper(Text.Trim(Text.Clean(_))), type text},
						{"NombreLider", each if _ = null then _ else Text.Proper(Text.Trim(Text.Clean(_))), type text},
						{"NombreFormador", each if _ = null then _ else Text.Proper(Text.Trim(Text.Clean(_))), type text}
					}),
					AliasLiderJuanEsteban = {"Juan Esteban Perez Camargo", "Juan Esteban Pérez Caramargo", "Juan Esteban Camargo", "Juan Esteban Cámargo"},
					LiderConsolidado = Table.TransformColumns(NombresPersonaNormalizados, {{"NombreLider", each if _ <> null and List.Contains(AliasLiderJuanEsteban, _) then "Juan Esteban Pérez Camargo" else _, type text}}),
					ColumnasCategoricasSinDato = {"CallCenter", "Jornada", "NombreAsesor", "NombreLider", "NombreFormador", "Duracion"},
					NulosCategoricosMarcados = Table.ReplaceValue(LiderConsolidado, null, "Sin dato", Replacer.ReplaceValue, ColumnasCategoricasSinDato),
					ValoresSinComentario = {"N/A", "NA", "NADA", "NINGUNA", "NO", "SIN OBSERVACIONES"},
					ComentarioUnificado = Table.TransformColumns(NulosCategoricosMarcados, {{"Comentario", each if _ = null then "Sin comentario" else if Text.Trim(_) = "" then "Sin comentario" else if List.Contains(ValoresSinComentario, Text.Upper(Text.Trim(_))) then "Sin comentario" else Text.Trim(Text.Clean(_)), type text}}),
					LikertComoNumero = Table.TransformColumnTypes(ComentarioUnificado, {{"SatisfaccionGeneral", type number}, {"Claridad", type number}, {"Utilidad", type number}, {"Dinamismo", type number}}),
					TiposFinalesAplicados = Table.TransformColumnTypes(LikertComoNumero, {{"FechaHora", type datetime}, {"CallCenter", type text}, {"Jornada", type text}, {"NombreAsesor", type text}, {"NombreLider", type text}, {"NombreFormador", type text}, {"Duracion", type text}, {"Comentario", type text}, {"Fecha", type date}})
				in
					TiposFinalesAplicados
