table Fact_LegalizacionBonos

	column Fecha
		dataType: dateTime
		isNullable: false
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Fecha

	column Pusher
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: Pusher

	column Concepto
		dataType: string
		summarizeBy: none
		sourceColumn: Concepto

	column TipoIncentivo
		dataType: string
		summarizeBy: none
		sourceColumn: TipoIncentivo

	column ValorRecibido
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: ValorRecibido

	column ValorLegalizado
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: ValorLegalizado

	partition Fact_LegalizacionBonos = m
		mode: import
		source =
				let
					RutaFuente = RutaCarpetaData & "\BI - NUEVO.xlsx",
					Libro = Excel.Workbook(File.Contents(RutaFuente), null, true),
					HojaUnica = (Nombre as text) as table =>
						let Coincidencias = Table.SelectRows(Libro, each [Item] = Nombre and [Kind] = "Sheet")
						in if Table.RowCount(Coincidencias) = 1 then Table.PromoteHeaders(Coincidencias{0}[Data], [PromoteAllScalars = true]) else error "No se encontro una unica hoja " & Nombre & ".",
					NormalizarTexto = (Valor as any) as nullable text =>
						if Valor = null then null
						else
							let Texto = Text.Upper(Text.Trim(Text.Clean(Text.From(Valor))))
							in if Texto = "" then null else Texto,
					// Etiqueta publica por grupo PUSHER con las mismas anclas de R3; el nombre nominal no sale de esta consulta.
					Asignacion = HojaUnica("Asignacion_PUSHER"),
					AnclasPublicas = [#"COS" = "PUSHER 1", #"ONE CONTACT" = "PUSHER 2", #"CONTACTMASTER BPO" = "PUSHER 3"],
					Anclas = Table.SelectRows(
						Table.FromRecords(List.Transform(Table.ToRecords(Asignacion), (r) => [PusherOrigen = NormalizarTexto(r[PUSHER]), Pusher = Record.FieldOrDefault(AnclasPublicas, NormalizarTexto(r[DESCRIPCION_ALTAS]) ?? "", null)])),
						each [PusherOrigen] <> null and [Pusher] <> null),
					MapaPusher = Table.Distinct(Anclas),
					MapaValidado =
						if Table.RowCount(MapaPusher) = 3 and List.Count(List.Distinct(MapaPusher[PusherOrigen])) = 3
						then MapaPusher
						else error "La equivalencia PUSHER de Asignacion_PUSHER no es univoca.",
					Encabezados = HojaUnica("Legalización_Bonos"),
					ColumnasRequeridas = {"Fecha", "Mes", "PUSHER", "Concepto", "Tipo de incentivo", "Valor recibido", "Valor legalizado"},
					ColumnasFaltantes = List.Difference(ColumnasRequeridas, Table.ColumnNames(Encabezados)),
					ConEsquemaValido =
						if List.IsEmpty(ColumnasFaltantes)
						then Table.SelectColumns(Encabezados, ColumnasRequeridas)
						else error "Faltan columnas obligatorias en Legalización_Bonos: " & Text.Combine(ColumnasFaltantes, ", "),
					FilasConDatos = Table.SelectRows(ConEsquemaValido, each [Fecha] <> null),
					Renombradas = Table.RenameColumns(FilasConDatos, {{"PUSHER", "PusherOrigen"}, {"Tipo de incentivo", "TipoIncentivo"}, {"Valor recibido", "ValorRecibido"}, {"Valor legalizado", "ValorLegalizado"}}),
					Normalizadas = Table.TransformColumns(Renombradas, {
						{"Fecha", each Date.From(_), type date},
						{"Mes", NormalizarTexto, type nullable text},
						{"PusherOrigen", NormalizarTexto, type nullable text},
						{"Concepto", NormalizarTexto, type nullable text},
						{"TipoIncentivo", NormalizarTexto, type nullable text},
						// Vacio en la fuente permanece null; no se convierte en cero.
						{"ValorRecibido", each if _ = null or _ = "" then null else Int64.From(_), Int64.Type},
						{"ValorLegalizado", each if _ = null or _ = "" then null else Int64.From(_), Int64.Type}
					}),
					Meses = {"ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"},
					MesInconsistente = Table.SelectRows(Normalizadas, each [Mes] <> Meses{Date.Month([Fecha]) - 1}),
					ConMesValidado = if Table.IsEmpty(MesInconsistente) then Normalizadas else error "Legalización_Bonos tiene Mes inconsistente con Fecha.",
					ConPusher = Table.NestedJoin(ConMesValidado, {"PusherOrigen"}, MapaValidado, {"PusherOrigen"}, "Mapa", JoinKind.LeftOuter),
					PusherExpandido = Table.ExpandTableColumn(ConPusher, "Mapa", {"Pusher"}, {"Pusher"}),
					PusherValidado = if Table.IsEmpty(Table.SelectRows(PusherExpandido, each [Pusher] = null)) then PusherExpandido else error "Legalización_Bonos tiene PUSHER sin etiqueta publica.",
					ColumnasFinales = Table.SelectColumns(PusherValidado, {"Fecha", "Pusher", "Concepto", "TipoIncentivo", "ValorRecibido", "ValorLegalizado"}),
					TiposAplicados = Table.TransformColumnTypes(ColumnasFinales, {{"Fecha", type datetime}, {"Pusher", type text}, {"Concepto", type text}, {"TipoIncentivo", type text}, {"ValorRecibido", Int64.Type}, {"ValorLegalizado", Int64.Type}})
				in
					TiposAplicados

	annotation PBI_ResultType = Table
