table Fact_MotivacionActividad

	column FechaHora
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: FechaHora

	column CallCenter
		dataType: string
		summarizeBy: none
		sourceColumn: CallCenter

	column Jornada
		dataType: string
		summarizeBy: none
		sourceColumn: Jornada

	column SatisfaccionGeneral
		dataType: double
		summarizeBy: none
		sourceColumn: SatisfaccionGeneral

	column ClaridadUtilidad
		dataType: double
		summarizeBy: none
		sourceColumn: ClaridadUtilidad

	column MotivacionPostActividad
		dataType: double
		summarizeBy: none
		sourceColumn: MotivacionPostActividad

	column AmbienteEquipo
		dataType: string
		summarizeBy: none
		sourceColumn: AmbienteEquipo

	column TipoActividadPreferida
		dataType: string
		summarizeBy: none
		sourceColumn: TipoActividadPreferida

	column Comentario
		dataType: string
		summarizeBy: none
		sourceColumn: Comentario

	column Fecha
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Fecha

	partition Fact_MotivacionActividad = m
		mode: import
		source =
				let
					Origen = EncuestaMotivacion_Limpio,
					ColumnasRenombradas = Table.RenameColumns(Origen, {
						{"Timestamp", "FechaHora"},
						{"¿En qué call center trabajas?", "CallCenter"},
						{"¿En qué jornada participaste?", "Jornada"},
						{"En general, ¿Qué tan satisfecho/a quedaste con la actividad?", "SatisfaccionGeneral"},
						{"La actividad fue clara, dinámica y útil para tu trabajo.", "ClaridadUtilidad"},
						{"Después de la actividad, ¿te sentiste más motivado/a para vender?", "MotivacionPostActividad"},
						{"¿Cómo describirías el ambiente de tu equipo?", "AmbienteEquipo"},
						{"¿Qué tipo de actividades crees que funcionan mejor con tu equipo?", "TipoActividadPreferida"},
						{"¿Qué mejorarías o qué actividad te gustaría para una próxima visita?", "Comentario"}
					}),
					ColumnaSinDatosEliminada = Table.RemoveColumns(ColumnasRenombradas, {"Nombre completo (Mayúscula)"}),
					ValoresSinComentario = {"N/A", "NA", "NADA", "NINGUNA", "NO", "SIN OBSERVACIONES"},
					ComentarioUnificado = Table.TransformColumns(ColumnaSinDatosEliminada, {{"Comentario", each if _ = null then "Sin comentario" else if Text.Trim(_) = "" then "Sin comentario" else if List.Contains(ValoresSinComentario, Text.Upper(Text.Trim(_))) then "Sin comentario" else Text.Trim(Text.Clean(_)), type text}}),
					LikertComoNumero = Table.TransformColumnTypes(ComentarioUnificado, {{"SatisfaccionGeneral", type number}, {"ClaridadUtilidad", type number}, {"MotivacionPostActividad", type number}}),
					TiposFinalesAplicados = Table.TransformColumnTypes(LikertComoNumero, {{"FechaHora", type datetime}, {"CallCenter", type text}, {"Jornada", type text}, {"AmbienteEquipo", type text}, {"TipoActividadPreferida", type text}, {"Comentario", type text}, {"Fecha", type date}})
				in
					TiposFinalesAplicados
