table Fact_AltasTeResuelve

	column FechaAlta
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: FechaAlta

	column AliadoKey
		dataType: string
		summarizeBy: none
		sourceColumn: AliadoKey

	column Altas
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Altas

	partition Fact_AltasTeResuelve = m
		mode: import
		source =
				let
					FilasValidas = Table.SelectRows(AltasTeResuelve_Limpio, each [EstadoFila] = "Valida"),
					ConAliadoKey = Table.AddColumn(FilasValidas, "AliadoKey", each [Descripcion], type text),
					ColumnasFinales = Table.SelectColumns(ConAliadoKey, {"FechaAlta", "AliadoKey", "Altas"}),
					TiposAplicados = Table.TransformColumnTypes(ColumnasFinales, {{"FechaAlta", type date}, {"AliadoKey", type text}, {"Altas", Int64.Type}})
				in
					TiposAplicados
