table Fact_MotivacionActividad
	lineageTag: 956639ed-b12e-4e67-92d2-04f2ac4ff6be

	column FechaHora
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e62c1c3-d877-4a1c-ab58-541280691ba8
		summarizeBy: none
		sourceColumn: FechaHora

	column CallCenter
		dataType: string
		lineageTag: 3bbcbb21-5b9b-4b5e-acfa-41dbb4990727
		summarizeBy: none
		sourceColumn: CallCenter

	column Jornada
		dataType: string
		lineageTag: d7410834-926f-4881-9210-feba1b962bf2
		summarizeBy: none
		sourceColumn: Jornada

	column SatisfaccionGeneral
		dataType: double
		lineageTag: 2d89fb88-1e31-451b-a0f0-a5c46427a7fa
		summarizeBy: none
		sourceColumn: SatisfaccionGeneral

	column ClaridadUtilidad
		dataType: double
		lineageTag: dc04690c-e8aa-4b14-969c-f41e0bfb1734
		summarizeBy: none
		sourceColumn: ClaridadUtilidad

	column MotivacionPostActividad
		dataType: double
		lineageTag: 61da83e7-a17c-4b96-9e2e-aa6480e2685f
		summarizeBy: none
		sourceColumn: MotivacionPostActividad

	column AmbienteEquipo
		dataType: string
		lineageTag: 3436779e-690c-414a-bcb6-1b30553e03a8
		summarizeBy: none
		sourceColumn: AmbienteEquipo

	column TipoActividadPreferida
		dataType: string
		lineageTag: 9f299a03-c22d-4ec4-8c80-ce4e4ace7118
		summarizeBy: none
		sourceColumn: TipoActividadPreferida

	column Comentario
		dataType: string
		lineageTag: 4507c644-ffd5-47ba-a0c3-291c568d2247
		summarizeBy: none
		sourceColumn: Comentario

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: ab7d3961-0585-4c09-b32f-dd7582587b60
		summarizeBy: none
		sourceColumn: Fecha

	partition Fact_MotivacionActividad = m
		mode: import
		lineageTag: da87cfc5-8c8d-4445-bbfa-35c9220ecc97
		source =
				let
					Origen = EncuestaMotivacion_Limpio,
					ColumnasRenombradas = Table.RenameColumns(Origen, {
						{"Timestamp", "FechaHora"},
						{"¿En qué call center trabajas?", "CallCenter"},
						{"¿En qué jornada participaste?", "Jornada"},
						{"En general, ¿Qué tan satisfecho/a quedaste con la actividad?", "SatisfaccionGeneral"},
						{"La actividad fue clara, dinámica y útil para tu trabajo.", "ClaridadUtilidad"},
						{"Después de la actividad, ¿te sentiste más motivado/a para vender?", "MotivacionPostActividad"},
						{"¿Cómo describirías el ambiente de tu equipo?", "AmbienteEquipo"},
						{"¿Qué tipo de actividades crees que funcionan mejor con tu equipo?", "TipoActividadPreferida"},
						{"¿Qué mejorarías o qué actividad te gustaría para una próxima visita?", "Comentario"}
					}),
					ColumnaSinDatosEliminada = Table.RemoveColumns(ColumnasRenombradas, {"Nombre completo (Mayúscula)"}),
					ValoresSinComentario = {"N/A", "NA", "NADA", "NINGUNA", "NO", "SIN OBSERVACIONES"},
					ComentarioUnificado = Table.TransformColumns(ColumnaSinDatosEliminada, {{"Comentario", each if _ = null then "Sin comentario" else if Text.Trim(_) = "" then "Sin comentario" else if List.Contains(ValoresSinComentario, Text.Upper(Text.Trim(_))) then "Sin comentario" else Text.Trim(Text.Clean(_)), type text}}),
					LikertComoNumero = Table.TransformColumnTypes(ComentarioUnificado, {{"SatisfaccionGeneral", type number}, {"ClaridadUtilidad", type number}, {"MotivacionPostActividad", type number}}),
					TiposFinalesAplicados = Table.TransformColumnTypes(LikertComoNumero, {{"FechaHora", type datetime}, {"CallCenter", type text}, {"Jornada", type text}, {"AmbienteEquipo", type text}, {"TipoActividadPreferida", type text}, {"Comentario", type text}, {"Fecha", type date}})
				in
					TiposFinalesAplicados
