table Fact_AltasTeResuelve
	lineageTag: 0f8a7b55-6ce7-4380-9b45-c33b151c881f

	column FechaAlta
		dataType: dateTime
		formatString: Short Date
		lineageTag: 40bd6df5-72de-42d8-af5c-fc904b442137
		summarizeBy: none
		sourceColumn: FechaAlta

		annotation UnderlyingDateTimeDataType = Date

	column AliadoKey
		dataType: string
		lineageTag: e23b07e1-c353-412c-87c6-3c2a9bd0e324
		summarizeBy: none
		sourceColumn: AliadoKey

	column Altas
		dataType: int64
		formatString: 0
		lineageTag: b5053060-3bc1-46fb-a945-6e7085d23bec
		summarizeBy: sum
		sourceColumn: Altas

	column PeriodoAliadoKey
		dataType: string
		isHidden
		isNullable: false
		lineageTag: d4a505b8-e395-41e7-83b4-807d630d8537
		summarizeBy: none
		sourceColumn: PeriodoAliadoKey

	partition Fact_AltasTeResuelve = m
		mode: import
		source =
				let
				    FilasValidas = Table.SelectRows(AltasTeResuelve_Limpio, each [EstadoFila] = "Valida"),
				    ConAnioMesClave = Table.AddColumn(
				        FilasValidas,
				        "AnioMesClave",
				        each Date.Year(Date.From([FechaAlta])) * 100 + Date.Month(Date.From([FechaAlta])),
				        Int64.Type
				    ),
				    ConPeriodoAliadoKey = Table.AddColumn(
				        ConAnioMesClave,
				        "PeriodoAliadoKey",
				        each Text.From([AnioMesClave], "en-US") & "|" & [AliadoKey],
				        type text
				    ),
				    ColumnasFinales = Table.SelectColumns(
				        ConPeriodoAliadoKey,
				        {"FechaAlta", "AliadoKey", "Altas", "PeriodoAliadoKey"}
				    ),
				    TiposAplicados = Table.TransformColumnTypes(
				        ColumnasFinales,
				        {
				            {"FechaAlta", type date},
				            {"AliadoKey", type text},
				            {"Altas", Int64.Type},
				            {"PeriodoAliadoKey", type text}
				        }
				    )
				in
				    TiposAplicados

	annotation PBI_ResultType = Table
