table Fact_CalidadLlamadas

	column FechaHora
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: FechaHora

	column CallCenter
		dataType: string
		summarizeBy: none
		sourceColumn: CallCenter

	column NombreAsesor
		dataType: string
		summarizeBy: none
		sourceColumn: NombreAsesor

	column NombreLider
		dataType: string
		summarizeBy: none
		sourceColumn: NombreLider

	column NombreAuditor
		dataType: string
		summarizeBy: none
		sourceColumn: NombreAuditor

	column Preg_TonoSaludo
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_TonoSaludo

	column Preg_FraseImpacto
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_FraseImpacto

	column Preg_PreguntasNecesidad
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_PreguntasNecesidad

	column Preg_ConexionBeneficio
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_ConexionBeneficio

	column Preg_ExplicacionProducto
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_ExplicacionProducto

	column Preg_ManejoObjeciones
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_ManejoObjeciones

	column Preg_CierreComercial
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_CierreComercial

	column Preg_ConfirmacionCierre
		dataType: double
		summarizeBy: none
		sourceColumn: Preg_ConfirmacionCierre

	column ObjecionPrincipal
		dataType: string
		summarizeBy: none
		sourceColumn: ObjecionPrincipal

	column TerminoEnVenta
		dataType: string
		summarizeBy: none
		sourceColumn: TerminoEnVenta

	column Observaciones
		dataType: string
		summarizeBy: none
		sourceColumn: Observaciones

	column Fecha
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Fecha

	partition Fact_CalidadLlamadas = m
		mode: import
		source =
				let
					Origen = MatrizCalidad_Limpio,
					ColumnasRenombradas = Table.RenameColumns(Origen, {
						{"Timestamp", "FechaHora"},
						{"CALL CENTER", "CallCenter"},
						{"Nombre del asesor", "NombreAsesor"},
						{"Líder / supervisor", "NombreLider"},
						{"Auditor / PUSHER", "NombreAuditor"},
						{"¿El asesor inició la llamada con buen tono, saludo, energía y seguridad?", "Preg_TonoSaludo"},
						{"¿Usó una frase de impacto para introducir la oferta?", "Preg_FraseImpacto"},
						{"¿Realizó preguntas para descubrir la necesidad del cliente?", "Preg_PreguntasNecesidad"},
						{"¿Conectó la necesidad del cliente con el beneficio del producto?", "Preg_ConexionBeneficio"},
						{"¿Explicó claramente qué incluye el producto sin saturar?", "Preg_ExplicacionProducto"},
						{"¿Manejó adecuadamente las objeciones del cliente?", "Preg_ManejoObjeciones"},
						{"¿Realizó cierre comercial sin presionar?", "Preg_CierreComercial"},
						{"¿Confirmó condiciones, aceptación y cerró con calidad?", "Preg_ConfirmacionCierre"},
						{"Objeción principal del cliente", "ObjecionPrincipal"},
						{"¿La llamada terminó en venta?", "TerminoEnVenta"}
					}),
					NAsComoNulos = Table.ReplaceValue(ColumnasRenombradas, "N/A", null, Replacer.ReplaceValue, {"Preg_TonoSaludo", "Preg_FraseImpacto", "Preg_PreguntasNecesidad", "Preg_ConexionBeneficio", "Preg_ExplicacionProducto", "Preg_ManejoObjeciones", "Preg_CierreComercial", "Preg_ConfirmacionCierre"}),
					PreguntasComoNumero = Table.TransformColumnTypes(NAsComoNulos, {{"Preg_TonoSaludo", type number}, {"Preg_FraseImpacto", type number}, {"Preg_PreguntasNecesidad", type number}, {"Preg_ConexionBeneficio", type number}, {"Preg_ExplicacionProducto", type number}, {"Preg_ManejoObjeciones", type number}, {"Preg_CierreComercial", type number}, {"Preg_ConfirmacionCierre", type number}}),
					TiposFinalesAplicados = Table.TransformColumnTypes(PreguntasComoNumero, {{"FechaHora", type datetime}, {"CallCenter", type text}, {"NombreAsesor", type text}, {"NombreLider", type text}, {"NombreAuditor", type text}, {"ObjecionPrincipal", type text}, {"TerminoEnVenta", type text}, {"Observaciones", type text}, {"Fecha", type date}})
				in
					TiposFinalesAplicados
